### ISSUE TITLE
Unable to use geben-helm-projectile-open-file

### ISSUE THREAD

**Issue by eric-hansen** [ahungry/geben-helm-projectile#2]
Using Emacs 25.2.1, PHP 5.5.38, helm-projectile 0.14.0

1.  Can't use `geben-helm-projectile/open-file` but instead `geben-helm-projectile-open-file` (otherwise get told that the command isn't found)
2.  When I run this command, nothing happens (buffer just closes), and nothing shows in *Messages* buffer

I've tried w/ and w/o starting geben before running this command.  Same result.

I can run geben without using this, but it's quite annoying to not use helm-projectile when that's what I use for everything.

**Comment by ahungry** [comment]
So, the readme is outdated (it should refer to `geben-helm-projectile-open-file` as this was a change to follow more standard Emacs conventions in elisp naming), however the file list should work properly, but it will be dependent on the file beginning the debug session being present in a project.

For instance, if I create a new file such as:

    /tmp/geben.php

And start geben with `M-x geben` and run the file with ` php -d xdebug.remote_enable=on -d xdebug.remote_host=127.0.0.1 -d xdebug.remote_port=9000 -d xdebug.remote_handler=dbgp -d xdebug.idekey=geben -d xdebug.remote_autostart=On /tmp/geben.php` you'll notice the list presented is empty (it won't give a prompt to hop into a project, which may be an enhancement I should add...

However, if you do the same and start a file in, say, `/tmp/ghp/geben.php` and make sure to git init and commit the file, and run the same command pointed there, the list will show geben.php as a selection candidate.

I'll update the readme tonight to fix the deprecated function reference and look into adding project select.
